<?php
$mod_name = 'Simple SEO';
$mod_version = 'v1.00';
$mod_machine_name = 'simpleseo';
$mod_description = 'Modul pridá ku kontentu keywords a description meta značky';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 0;
$mod_content_extension = 1;
$mod_module_extension = 0;
$mod_application = 0;