<?php
$mod_name = 'Categories';
$mod_version = 'v1.00';
$mod_machine_name = 'categories';
$mod_description = 'Modul umoznuje kategorizaciu obsahu.';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;