<?php
/**
 * v1.00
 */

$mod_name = 'Web formulár';
$mod_version = 'v1.00';
$mod_machine_name = 'webform';
$mod_description = 'Modul web formulár Vám umožnuje vytvoriť užívateľský formulár a návševníci vašej stránky cez neho môžu odoslať správu na váš email.
                    Po inštalácii sa v administračnom menu -> moduly vytvorí odkaz Web formulár.';
/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;