<?
/******* ERRORS *******/
define('ERROR_TITLE','ERROR!');
define('YOU_HAVE_NOT_PERMISSION','You have no permission to run this action.');
define('CONTENT_NOT_EXISTS','You are trying to access unexisting content.');
define('CONTENT_NOT_EXIST_FOR_LANG','Content does not exist for this language.');
define('NO_PERMISSION_TO_SEE_CONTENT','You have no permission to watch this content.');
define('UNDEFINED_ERROR','Undefined error.');
