<?
/******* ERRORS *******/
define('ERROR_TITLE','ERROR!');
define('YOU_HAVE_NOT_PERMISSION','You have no permission to run this action.');
define('CONTENT_NOT_EXISTS','You are trying to access unexisting content.');
define('CONTENT_NOT_EXIST_FOR_LANG','Content does not exist for this language.');
define('NO_PERMISSION_TO_SEE_CONTENT','You have no permission to watch this content.');
define('UNDEFINED_ERROR','Undefined error.');

/******* REGISTRATION *****/
define('REGISTRATION_SHOW_TITLE','Registration');
define('REGISTRATION_SHOW_INFO','After registration you will be able to use tools for reporting your activity on IVAO networks - flown tour legs, events activity. You also can sign for newsletter or enable the Events Reminder.');
define('REGISTRATION_FORM_USER','IVAO VID:');
define('REGISTRATION_FORM_USER_RULE_FILLED','Fill IVAO VID.');
define('REGISTRATION_FORM_USER_RULE_INTEGER','IVAO VID must be integer number.');
define('REGISTRATION_FORM_PASSWORD_RULE_FILLED','Fill the password.');
define('REGISTRATION_FORM_PASSWORD_RULE_REGEX','The password must contain from 6 to 24 characters.');
define('REGISTRATION_FORM_PWD_CONFIRM','Confirm password:');
define('REGISTRATION_FORM_PASSWORD_RULE_EQUAL','Password confirmation must be the same as filled password.');
define('REGISTRATION_FORM_NAME_RULE_FILLED','Fill the name.');
define('REGISTRATION_FORM_SURNAME_RULE_FILLED','Fill the surname.');
define('REGISTRATION_FORM_EMAIL_RULE_EMAIL','Fill a correct email');
define('REGISTRATION_FORM_NEWSLETTER','Sign for newsletter');
define('REGISTRATION_FORM_EVENTS_REMINDER','Enable the Event Reminder');
define('REGISTRATION_FORM_CAPTCHA','Secure code');
define('REGISTRATION_FORM_CAPTCHA_RULE','Fill the right secure code');
define('REGISTRATION_FORM_PROFILE','Something about me');
define('REGISTRATION_FORM_PROFILE_DESC','You can write something about you, your hobbies, what you fly with, etc ...');
define('REGISTRATION_PROFILE_CREATED','The registration was successfull');

/******** USER ***********/
define('USER_SHOW_TITLE','Profile');
define('USER_STAFF_MEMBER','Staff member');
define('USER_STAFF_POSITION','Staff position');
define('USER_MY_BLOG','My Blog');
define('USER_MY_PHOTOALBUMS','My Photoalbumes');
define('USER_EDIT_PROFILE_TITLE','My Profile');
define('USER_CHANGES_WERE_SAVED', 'Changes were saved.');
define('USER_EMAIL_ERROR', 'Change your Email. This one is used.');

define('USER_ERROR_NO_PROFILE','The searched profile does not exist.');
