<?
/******* ERRORS *******/
define('ERROR_TITLE','POZOR!');
define('YOU_HAVE_NOT_PERMISSION','Nemáte oprávnenie vykonat túto akciu.');
define('CONTENT_NOT_EXISTS','Snažíte sa zobraziť neexistujúci obsah.');
define('CONTENT_NOT_EXIST_FOR_LANG','Obsah neexistuje pre tento jazyk.');
define('NO_PERMISSION_TO_SEE_CONTENT','Nemáte povolenie prezerať tento obsah.');
define('UNDEFINED_ERROR','Nedefinovaná chyba.');

/******* REGISTRATION *****/
define('REGISTRATION_SHOW_TITLE','Registrácia');
define('REGISTRATION_SHOW_INFO','Po registrácii ti budú dostupné nástroje na reportovanie tvojej aktivity na sieti IVAO - odletené legy z túr, učasť na eventoch. Zároveň sa možeš prihlásiť na odber noviniek alebo si zapnúť pripomínanie eventov.');
define('REGISTRATION_FORM_USER','IVAO VID:');
define('REGISTRATION_FORM_USER_RULE_FILLED','Vyplňte IVAO VID.');
define('REGISTRATION_FORM_USER_RULE_INTEGER','IVAO VID musí byť celé číslo.');
define('REGISTRATION_FORM_PASSWORD_RULE_FILLED','Vyplňte heslo.');
define('REGISTRATION_FORM_PASSWORD_RULE_REGEX','Heslo musí mať od 6 do 24 znakov.');
define('REGISTRATION_FORM_PWD_CONFIRM','Potvrdenie hesla:');
define('REGISTRATION_FORM_PASSWORD_RULE_EQUAL','Potvrdenie hesla musí byť zhodné so zadaným heslom.');
define('REGISTRATION_FORM_NAME_RULE_FILLED','Vyplňte Meno.');
define('REGISTRATION_FORM_SURNAME_RULE_FILLED','Vyplňte Priezvisko.');
define('REGISTRATION_FORM_EMAIL_RULE_EMAIL','Zadajte korektný email.');
define('REGISTRATION_FORM_NEWSLETTER','Prihlásiť sa na odber noviniek');
define('REGISTRATION_FORM_EVENTS_REMINDER','Zapnúť pripomienku eventov');
define('REGISTRATION_FORM_CAPTCHA','Bezpečnostný kód');
define('REGISTRATION_FORM_CAPTCHA_RULE','Opíšte správne bezpečnostný kód');
define('REGISTRATION_FORM_PROFILE','Niečo o mne');
define('REGISTRATION_FORM_PROFILE_DESC','Napíš niečo o sebe, o tvojich záľubách, na čom rád lietaš, kde rád riadiš...');
define('REGISTRATION_PROFILE_CREATED','Registrácia prebehla úspešne.');

/******** USER ***********/
define('USER_SHOW_TITLE','Profil');
define('USER_STAFF_MEMBER','Člen staffu');
define('USER_STAFF_POSITION','Pozícia v staffe');
define('USER_MY_BLOG','Môj blog');
define('USER_MY_PHOTOALBUMS','Moje fotoalbumy');
define('USER_EDIT_PROFILE_TITLE','Môj profil');
define('USER_CHANGES_WERE_SAVED', 'Zmeny boli uložené.');
define('USER_EMAIL_ERROR', 'Zvolte iný email, tento sa už používa.');

define('USER_ERROR_NO_PROFILE','Hľadaný profil neexistuje');