<?php
/**
 * Module Simple SEO
 * created by Branislav Zvolenský
 * 27.11.2010
 *
 * language: English
 */
define('SIMPLE_SEO_SETTINGS', 'Simple SEO Settings');
define('SIMPLE_SEO_KEYWORDS_LABEL', 'Keywords <meta keywords>');
define('SIMPLE_SEO_KEYWORDS_DESC', 'Keywords separated by comma');
define('SIMPLE_SEO_DESCRIPTION_LABEL', 'Page description <meta description>');
define('SIMPLE_SEO_DESCRIPTION_DESC', 'This includes a brief description of the site, which appears in the search engines');
define('SIMPLE_SEO_ROBOTS_LABEL', 'Robots <meta robots>');
define('SIMPLE_SEO_ROBOTS_DESC', 'Allowed pairs of values: index,follow / index,nofollow / noindex,nofollow');