<?php
/**
 * Module Simple SEO
 * created by Branislav Zvolenský
 * 27.11.2010
 *
 * language: Hungarian
 */
define('SIMPLE_SEO_SETTINGS', 'Simple SEO beállítások');
define('SIMPLE_SEO_KEYWORDS_LABEL', 'Kulcsszavak <meta keywords>');
define('SIMPLE_SEO_KEYWORDS_DESC', 'Kulcsszavak vesszővel elválasztva');
define('SIMPLE_SEO_DESCRIPTION_LABEL', 'Weboldal leírás <meta description>');
define('SIMPLE_SEO_DESCRIPTION_DESC', 'Ide kerülnek a rövid leírást az oldal, amely megjelenik a keresőmotorok');
define('SIMPLE_SEO_ROBOTS_LABEL', 'Robotok <meta robots>');
define('SIMPLE_SEO_ROBOTS_DESC', 'Megengedett pár értékek: index,follow / index,nofollow / noindex,nofollow');