<?php
/**
 * Module Simple SEO
 * created by Branislav Zvolenský
 * 27.11.2010
 *
 * language: Slovak
 */
define('SIMPLE_SEO_SETTINGS', 'Nastavenia Simple SEO');
define('SIMPLE_SEO_KEYWORDS_LABEL', 'Kľúčové slová <meta keywords>');
define('SIMPLE_SEO_KEYWORDS_DESC', 'Klúčové slová oddelené čiarkou');
define('SIMPLE_SEO_DESCRIPTION_LABEL', 'Popis stránky <meta description>');
define('SIMPLE_SEO_DESCRIPTION_DESC', ' Vložte sem krátky popis stránky, ktorý sa bude zobrazovať vo vyhladávačoch.');
define('SIMPLE_SEO_ROBOTS_LABEL', 'Roboty <meta robots>');
define('SIMPLE_SEO_ROBOTS_DESC', 'Povolené páry hodnôt: index,follow / index,nofollow / noindex,nofollow');