<?php
$mod_name = 'Texyla';
$mod_version = 'v1.00';
$mod_machine_name = 'texyla';
$mod_description = 'jQuery WYSIWYM (What You See Is What You Mean) editor pre knižnicu TEXY. Možnosť nastaviť na všetky alebo konkrétne textarey. Vyžaduje inštaláciu jQuery UI.';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 0;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 1;