<?php
$mod_name = 'Template';
$mod_version = 'v1.00';
$mod_machine_name = 'template';
$mod_description = 'This is the sceleton for module construction. You can find it on file system /document_root/app/modules/template';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;