<?php
/**
 * this file should consist of installation and uninstallation rutines such as:
 * table creating, table removing,
 * inserting initial records etc.
 */

/***************************************** INSTALLATION ROUTINE ***/
  function moduleInstall()
  {
    	
      
	
  }
  
/***************************************** UNINSTALLATION ROUTINE ***/
  function moduleUninstall()
  {
      
      
      
  }