<?php
$mod_name = 'Novinky';
$mod_version = 'v1.00';
$mod_machine_name = 'novinky';
$mod_description = 'Modul novinky slúži na zobrazovanie krátkych textových správ. Po inštalácii sa v administračnom menu zobrazí položka Novinky, kde môžete meniť nastavenia. Pred inštaláciou si prečítajte ReadMe.txt v adresáry app/modules/novinky.';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;