<?php
$mod_name = 'Produkty';
$mod_version = 'v1.50';
$mod_machine_name = 'produkty';
$mod_description = 'Modul Produkty vytvorí Katalóg produktov. Prístup k nastaveniam nájdete v administračnom menu Moduly -> Produkty -> Nastavenia.';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;