<?
/**************** WEB FORM (English) *****************/

define('WF_ADMIN_TITLE', 'Web form - administration');

define('WF_FIELDS_TITLE', 'Form Fields');

define('WF_ADMIN_TPL_MESSAGES_ADMINISTRATION', 'Administration');
define('WF_ADMIN_TPL_MESSAGES_SETTINGS', 'Settings of sent messages');
define('WF_ADMIN_TPL_MESSAGES_HISTORY', 'History of sent messages');
define('WF_ADMIN_TPL_ADD_FORM', 'Add Form');
define('WF_ADMIN_TPL_NO_FORMS', 'There are no forms created.');

define('WF_SAVE_NEW_FORM_SAVED', 'Form was saved.');
define('WF_SAVE_NEW_FORM_SAVE_FAILED', 'Saving of form failed');

define('WF_RENDER_SHOW_OPEN_FORM', 'Open form');
define('WF_RENDER_DEFAULT_SEND_FROM', 'Sent form form: ');
define('WF_RENDER_ADD_TITLE', 'New Web Form');
define('WF_RENDER_EDIT_TITLE', 'Web form - Editation');
define('WF_RENDER_SETTINGS_TITLE', 'Web form - Settings of sent messages');
define('WF_RENDER_EDIT_FIELD_TITLE', 'Field Editation ');

define('WF_ACTION_SEND_SEND_MESSAGE', 'The message was sent, thank you.');
define('WF_ACTION_SEND_SEND_FAILED_MESSAGE', 'Sending of message failed.');

define('WF_ACTION_SEND_MESSAGE_FROM', 'Message from form: ');

define('WF_ACTION_ORDER_FIELDS_OK', 'The order was changed.');
define('WF_ACTION_ORDER_FIELDS_FAILED', 'Saving of order failed');

define('WF_CREATE_WEB_FORM_CAPTCHA_LABEL', 'Write the secure code from image');
define('WF_CREATE_WEB_FORM_CAPTCHA_RULE', 'Write the secure code correctly.');
define('WF_CREATE_WEB_FORM_NUMERIC_RULE', 'must be integer number.');
define('WF_CREATE_WEB_FORM_MIN_RULE', 'it must be minimally ');
define('WF_CREATE_WEB_FORM_MAX_RULE', 'it must be maximally ');
define('WF_CREATE_WEB_FORM_RANGE_RULE', 'it must be between ');
define('WF_CREATE_WEB_FORM_EMAIL_RULE', 'must be correct email address');
define('WF_CREATE_WEB_FORM_NO_FIELDS', 'There are no field for this form else.');

// ADD END EDIT FORM
define('WF_FRM_TITLE_RULE', 'Fill item Title.');
define('WF_FRM_FORM_TITLE_LABEL', 'Form Title');
define('WF_FRM_FORM_TITLE_DESC', 'Fill if you want have title above the form.');
define('WF_FRM_BODY_DESC', 'It will appear after the form. If you want have the body in front of th form, select the option <i>Place form after body</i>.');
define('WF_FRM_FORM_AFTER_TEXT_LABEL', 'Place form after body');
define('WF_FRM_HIDE_ON_LOAD_LABEL', 'Hide form on load');
define('WF_FRM_PATH_ALIAS_RULE', 'URL alias may contain only letters (without accents), numbers, underscores and hyphens.');
define('WF_FRM_EMAIL_RULE', 'Enter a correct email address.');

define('WF_FRM_ADD_NEW_FIELD', 'Add a new field');
define('WF_FRM_FIELDS_TITLE_RULE', 'Fill itme Title');
define('WF_FRM_FIELDS_FIELDTYPE_LABEL', 'Select a type of field');
define('WF_FRM_FIELDS_FRM_NAME_LABEL', 'Machine name of form item name');
define('WF_FRM_FIELDS_FRM_NAME_RULE', 'Fill Machine name of form item name');
define('WF_FRM_FIELDS_FRM_NAME_REGEX_RULE', 'Machine name must contain english letters, numbers and underscores only');
define('WF_FRM_FIELDS_FRM_NAME_DESC', 'Machine name must contain english letters, numbers and underscores only.');
define('WF_FRM_FIELDS_SAVE_LABEL', 'Add a new field');

define('MENU_TITLE_LABEL', 'Title in Menu');
define('MENU_TITLE_DESC', 'Fill title that appears as menu item. If you do not want to put this content to the menu, leave blank.');
define('MENU_ITEMS_LABEL', 'Parent menu item');
define('MENU_ITEMS_DESC', 'Select or change parent menu item.');
define('MENU_SETTINGS', 'Menu Settings');

//ERRORS
define('WF_ERR_PATH_ALIAS_PART_ONE', 'Filled URL alias');
define('WF_ERR_PATH_ALIAS_PART_TWO', 'exists yet.');
