<?
/**************** WEB FORM (Hungarian) *****************/

define('WF_ADMIN_TITLE', 'Webes űrlap - Adminisztráció');

define('WF_FIELDS_TITLE', 'Űrlapmezők ');

define('WF_ADMIN_TPL_MESSAGES_ADMINISTRATION', 'Administration');
define('WF_ADMIN_TPL_MESSAGES_SETTINGS', 'Beállításai üzenetek');
define('WF_ADMIN_TPL_MESSAGES_HISTORY', 'Történelem Az elküldött üzenetek');
define('WF_ADMIN_TPL_ADD_FORM', 'add webes űrlapot');
define('WF_ADMIN_TPL_NO_FORMS', 'Bár még nem hozott létre semmilyen formában.');

define('WF_SAVE_NEW_FORM_SAVED', 'Az űrlap megmenekült.');
define('WF_SAVE_NEW_FORM_SAVE_FAILED', 'Megtakarítási formát nem sikerült');

define('WF_RENDER_SHOW_OPEN_FORM', 'Nyílt formában');
define('WF_RENDER_DEFAULT_SEND_FROM', 'Kifüggesztett formában ');
define('WF_RENDER_ADD_TITLE', 'Új webes űrlap');
define('WF_RENDER_EDIT_TITLE', 'Web Form - frissítve');
define('WF_RENDER_SETTINGS_TITLE', 'Web formájában - üzenetre');
define('WF_RENDER_EDIT_FIELD_TITLE', 'Edit mező ');

define('WF_ACTION_SEND_SEND_MESSAGE', 'Üzenet elküldve, köszönöm.');
define('WF_ACTION_SEND_SEND_FAILED_MESSAGE', 'Üzenet küldése sikertelen.');

define('WF_ACTION_SEND_MESSAGE_FROM', 'Jelentés a forma ');

define('WF_ACTION_ORDER_FIELDS_OK', 'A rend megváltozott.');
define('WF_ACTION_ORDER_FIELDS_FAILED', 'Mentése érdekében nem');

define('WF_CREATE_WEB_FORM_CAPTCHA_LABEL', 'Írja be a biztonsági kódot');
define('WF_CREATE_WEB_FORM_CAPTCHA_RULE', 'Mutassa be a megfelelő biztonsági kódot.');
define('WF_CREATE_WEB_FORM_NUMERIC_RULE', 'meg kell egész számnak.');
define('WF_CREATE_WEB_FORM_MIN_RULE', 'legalább ');
define('WF_CREATE_WEB_FORM_MAX_RULE', 'Lehet, hogy a maximális érték ');
define('WF_CREATE_WEB_FORM_RANGE_RULE', 'kell a tartományban ');
define('WF_CREATE_WEB_FORM_EMAIL_RULE', 'helyesnek kell lennie, e-mail címét');
define('WF_CREATE_WEB_FORM_NO_FIELDS', 'Forma még mindig tartalmaz mezőket.');

// ADD END EDIT FORM
define('WF_FRM_TITLE_RULE', 'Kérjük, adja meg a cím.');
define('WF_FRM_FORM_TITLE_LABEL', 'Headline formában');
define('WF_FRM_FORM_TITLE_DESC', 'Teljes, ha meg akarom mutatni a formáját a címsort.');
define('WF_FRM_BODY_DESC', 'Formájában jelenik meg. Ha meg szeretné tekinteni az ilyen tartalom az űrlapot, kattintson a jelölőnégyzetre <i>Nézd formában szöveg</i>.');
define('WF_FRM_FORM_AFTER_TEXT_LABEL', 'Nézd formában szöveg');
define('WF_FRM_HIDE_ON_LOAD_LABEL', 'Űrlap elrejtése');
define('WF_FRM_PATH_ALIAS_RULE', 'URL alias május csak betűket tartalmaz (ékezetek nélkül), számokat, aláhúzást és kötőjelet.');
define('WF_FRM_EMAIL_RULE', 'Adja meg a helyes e-mail címre.');

define('WF_FRM_ADD_NEW_FIELD', 'Új mező hozzáadása');
define('WF_FRM_FIELDS_TITLE_RULE', 'Adja cím');
define('WF_FRM_FIELDS_FIELDTYPE_LABEL', 'Válassza ki a mező');
define('WF_FRM_FIELDS_FRM_NAME_LABEL', 'Név attribútum name formájában');
define('WF_FRM_FIELDS_FRM_NAME_RULE', 'Írja be a nevet attribútum name');
define('WF_FRM_FIELDS_FRM_NAME_REGEX_RULE', 'Név attribútum name csak betűket (ékezetek nélkül), számokat és aláhúzást');
define('WF_FRM_FIELDS_FRM_NAME_DESC', 'A gép neve. Május csak betűket tartalmaz (ékezetek nélkül), számokat és aláhúzást.');
define('WF_FRM_FIELDS_SAVE_LABEL', 'Új mező hozzáadása');

define('MENU_TITLE_LABEL', 'Headline a menüben');
define('MENU_TITLE_DESC', 'Írja be a címet, hogy jelenik meg a menüpont. Ha nem szúrja be a tételt a menüben, hagyja üresen.');
define('MENU_ITEMS_LABEL', 'Szülő elem');
define('MENU_ITEMS_DESC', 'Válassza ki vagy megváltoztatja a szülő elem.');
define('MENU_SETTINGS', 'Beállítások menü');

//ERRORS
define('WF_ERR_PATH_ALIAS_PART_ONE', 'A megadott URL alias');
define('WF_ERR_PATH_ALIAS_PART_TWO', 'már létezik.');
