<?
/**************** WEB FORM (Slovak) *****************/

define('WF_ADMIN_TITLE', 'Web formulár - administrácia');

define('WF_FIELDS_TITLE', 'Polia formulára ');

define('WF_ADMIN_TPL_MESSAGES_ADMINISTRATION', 'Administrácia');
define('WF_ADMIN_TPL_MESSAGES_SETTINGS', 'Nastavenia odoslaných správ');
define('WF_ADMIN_TPL_MESSAGES_HISTORY', 'História odoslaných správ');
define('WF_ADMIN_TPL_ADD_FORM', 'Pridať formulár');
define('WF_ADMIN_TPL_NO_FORMS', 'Zatiaľ nemáte vytvorené žiadne formuláre.');

define('WF_SAVE_NEW_FORM_SAVED', 'Formulár bol uložený.');
define('WF_SAVE_NEW_FORM_SAVE_FAILED', 'Ukladanie formuláru zlyhalo');

define('WF_RENDER_SHOW_OPEN_FORM', 'Otvoriť formulár');
define('WF_RENDER_DEFAULT_SEND_FROM', 'Odoslané z formulára ');
define('WF_RENDER_ADD_TITLE', 'Nový Web formulár');
define('WF_RENDER_EDIT_TITLE', 'Web formulár - úprava');
define('WF_RENDER_SETTINGS_TITLE', 'Web formulár - nastavenia odoslaných správ');
define('WF_RENDER_EDIT_FIELD_TITLE', 'Editácia poľa ');

define('WF_ACTION_SEND_SEND_MESSAGE', 'Správa bola odoslaná, ďakujeme.');
define('WF_ACTION_SEND_SEND_FAILED_MESSAGE', 'Odoslanie správy zlyhalo.');

define('WF_ACTION_SEND_MESSAGE_FROM', 'Správa z formulára ');

define('WF_ACTION_ORDER_FIELDS_OK', 'Poradie bolo zmenené.');
define('WF_ACTION_ORDER_FIELDS_FAILED', 'Ukladanie poradia zlyhalo');

define('WF_CREATE_WEB_FORM_CAPTCHA_LABEL', 'Opíšte bezpečnostný kód');
define('WF_CREATE_WEB_FORM_CAPTCHA_RULE', 'Opíšte správne bezpečnostný kód.');
define('WF_CREATE_WEB_FORM_NUMERIC_RULE', 'musí byť celé číslo');
define('WF_CREATE_WEB_FORM_MIN_RULE', 'musí mať hodnotu minimálne ');
define('WF_CREATE_WEB_FORM_MAX_RULE', 'môže mať hodnotu maximálne ');
define('WF_CREATE_WEB_FORM_RANGE_RULE', 'musí byť v rozpätí ');
define('WF_CREATE_WEB_FORM_EMAIL_RULE', 'musí byť korektná emailová adresa');
define('WF_CREATE_WEB_FORM_NO_FIELDS', 'Formulár ešte neobsahuje polia.');

// ADD END EDIT FORM
define('WF_FRM_TITLE_RULE', 'Vyplňte položku Titulok.');
define('WF_FRM_FORM_TITLE_LABEL', 'Titulok formulára');
define('WF_FRM_FORM_TITLE_DESC', 'Vyplňte, ak chcete, aby sa nad formulárom zobrazoval titulok.');
define('WF_FRM_BODY_DESC', 'Zobrazí sa za formulárom. Ak chcete, aby sa tento obsah zobrazil pred formulárom, zaškrtnite políčko <i>Zobraziť formulár za textom</i>.');
define('WF_FRM_FORM_AFTER_TEXT_LABEL', 'Zobraziť formulár za textom');
define('WF_FRM_HIDE_ON_LOAD_LABEL', 'Schovávať formulár');
define('WF_FRM_PATH_ALIAS_RULE', 'URL alias môže obsahovať iba písmená (bez diakritiky), číslice, podtržník a pomlčku.');
define('WF_FRM_EMAIL_RULE', 'Zadajte korektnú emailovú adresu.');

define('WF_FRM_ADD_NEW_FIELD', 'Pridať nové pole');
define('WF_FRM_FIELDS_TITLE_RULE', 'Zadajte Titulok');
define('WF_FRM_FIELDS_FIELDTYPE_LABEL', 'Vyberte typ poľa');
define('WF_FRM_FIELDS_FRM_NAME_LABEL', 'Meno atribútu name vo formuláre');
define('WF_FRM_FIELDS_FRM_NAME_RULE', 'Zadajte Meno atribútu name');
define('WF_FRM_FIELDS_FRM_NAME_REGEX_RULE', 'Meno atribútu name môže obsahovať iba písmená (bez diakritiky), číslice a podtržník');
define('WF_FRM_FIELDS_FRM_NAME_DESC', 'Strojové meno. Môže obsahovať iba písmená (bez diakritiky), číslice a podtržník');
define('WF_FRM_FIELDS_SAVE_LABEL', 'Pridať nové pole');

define('MENU_TITLE_LABEL', 'Titulok v menu');
define('MENU_TITLE_DESC', 'Zadajte titulok, ktorý sa bude zobrazovať ako položka menu. Ak nechcete vložiť položku do menu, nechajte prázdne.');
define('MENU_ITEMS_LABEL', 'Nadradená položka');
define('MENU_ITEMS_DESC', 'Zvoľte alebo zmente nadradenú položku.');
define('MENU_SETTINGS', 'Nastavenia menu');

//ERRORS
define('WF_ERR_PATH_ALIAS_PART_ONE', 'Zadaný URL alias');
define('WF_ERR_PATH_ALIAS_PART_TWO', 'už existuje.');
