<?php
$mod_name = 'Kniha návštev';
$mod_version = 'v1.10';
$mod_machine_name = 'guestbook';
$mod_description = 'Modul kniha návštev vytvorí návštevnú knihu. Po inštalácii sa v navigačnom a primárnom menu vytvorí odkaz Kniha návštev.';

/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;