<?php
/**
 * v1.10 - added phone field
 */

$mod_name = 'Kontaktný formulár';
$mod_version = 'v1.10';
$mod_machine_name = 'kontakt';
$mod_description = 'Modul Kontaktný formulár umožnuje návševníkom vašej stránky odoslať správu na váš email priamo z vašej stránky.
                    Po inštalácii sa v administračnom menu -> moduly vytvorí odkaz Kontaktný formulár.';
					
/** 
 * set options, they can be:
 * standalone,
 * content_extension - extends all content types,
 * module_extension - extends a module,
 * application - extends whole application
 */
$mod_standalone = 1;
$mod_content_extension = 0;
$mod_module_extension = 0;
$mod_application = 0;