<?
/******************* MODULE TEXYLA (English) *****************/
define('TEXYLA_ADMIN_TITLE', 'TEXYLA - Administration');
define('TEXYLA_ADMIN_CSS_NAME', 'CSS element (#id, .class)');
define('TEXYLA_ADMIN_DESC', 'Description');
define('TEXYLA_ADMIN_ADD_TEXTAREAS', 'Add a textarea on witch witch will be Texyla applied. Click on Add Textarea.');
define('TEXYLA_ADMIN_LNK_ADD_TEXTAREA', 'Add Textarea');

define('TEXYLA_ADD_TITLE', 'New Textarea');
define('TEXYLA_EDIT_TITLE', 'Textarea - editation');

define('TEXYLA_FRM_ADD_TEXYLA_LABEL', 'Put CSS Id or CSS Triedu');
define('TEXYLA_FRM_ADD_TEXYLA_DESC', 'CSS ID like <i>#cssId</i>, CSS Class like <i>.cssTrieda</i>. If you want to all textareas be affected then put: <i>textarea</i>.');
define('TEXYLA_FRM_ADD_TEXYLA_RULE', 'Fill item CSS id/class');
define('TEXYLA_FRM_ADD_DESCRIPTION_LABEL', 'Description (note)');

define('TEXYLA_FRM_ADD_ADMIN_SETTINGS_LABEL', 'Settings of Texyla for Administrators');
define('TEXYLA_FRM_ADD_EDITOR_SETTINGS_LABEL', 'Settings of Texyla for Editors');
define('TEXYLA_FRM_ADD_USER_SETTINGS_LABEL', 'Settings of Texyla for Users');
define('TEXYLA_FRM_ADD_VISITOR_SETTINGS_LABEL', 'Settings of Texyla for Visitors');
define('TEXYLA_FRM_ADD_ALLOW_LABEL', 'Allow Texyla for This Role');
define('TEXYLA_FRM_ADD_TEXYCFG_LABEL', 'Texy Configuration');
define('TEXYLA_FRM_ADD_BTLTOOLBAREDIT_LABEL', 'Edit Button');
define('TEXYLA_FRM_ADD_BTLTOOLBARPREVIEW_LABEL', 'Preview Button');
define('TEXYLA_FRM_ADD_BTLTOOLBARHTMLPREVIEW_LABEL', 'HTML Preview Button');
define('TEXYLA_FRM_ADD_BUTTONTYPE_LABEL', 'Button Type');
define('TEXYLA_FRM_ADD_TABS_LABEL', 'Tabs');
define('TEXYLA_FRM_ADD_HEADERS_LABEL', 'Headers');
define('TEXYLA_FRM_ADD_FONT_STYLE_LABEL', 'Font Styling');
define('TEXYLA_FRM_ADD_TEXT_ALIGN_LABEL', 'Text Alignment');
define('TEXYLA_FRM_ADD_LISTS_LABEL', 'Lists');
define('TEXYLA_FRM_ADD_LINK_LABEL', 'Links');
define('TEXYLA_FRM_ADD_IMG_LABEL', 'Image');
define('TEXYLA_FRM_ADD_TABLE_LABEL', 'Tables');
define('TEXYLA_FRM_ADD_EMOTICON_LABEL', 'Emoticons');
define('TEXYLA_FRM_ADD_SYMBOL_LABEL', 'Symbols');
define('TEXYLA_FRM_ADD_COLOR_LABEL', 'Colors');
define('TEXYLA_FRM_ADD_TEXTTRANSFORM_LABEL', 'Text Transformation');
define('TEXYLA_FRM_ADD_BLOCKS_LABEL', 'Blocks');
define('TEXYLA_FRM_ADD_CODES_LABEL', 'Codes Signs');
define('TEXYLA_FRM_ADD_OTHERS_LABEL', 'Others');
define('TEXYLA_FRM_ADD_ADMIN_CHECKS_LABEL', 'Options Bar for Administrator');
define('TEXYLA_FRM_ADD_EDITOR_CHECKS_LABEL', 'Options Bar for Editor');
define('TEXYLA_FRM_ADD_USER_CHECKS_LABEL', 'Options Bar for User');
define('TEXYLA_FRM_ADD_VISITOR_CHECKS_LABEL', 'Options Bar for Visitor');

// errors
define('TEXYLA_ERR_NO_ID', 'A record with this ID does not exists.');