<?
/******************* MODULE TEXYLA (Slovak) *****************/
define('TEXYLA_ADMIN_TITLE', 'TEXYLA - Administrácia');
define('TEXYLA_ADMIN_CSS_NAME', 'CSS označenie (id, trieda)');
define('TEXYLA_ADMIN_DESC', 'Popis');
define('TEXYLA_ADMIN_ADD_TEXTAREAS', 'Pridajte Textareu, nad ktorou sa zobrazí ovládanie Texyly, kliknutím na Pridať Textareu.');
define('TEXYLA_ADMIN_LNK_ADD_TEXTAREA', 'Pridať Textareu');

define('TEXYLA_ADD_TITLE', 'Nová Textarea');
define('TEXYLA_EDIT_TITLE', 'Textarea - editácia');

define('TEXYLA_FRM_ADD_TEXYLA_LABEL', 'Zadajte CSS Id alebo CSS Triedu');
define('TEXYLA_FRM_ADD_TEXYLA_DESC', 'CSS ID v tvare <i>#cssId</i>, CSS Trieda v tvare <i>.cssTrieda</i>. Ak chcete uplatniť na všetky Textarey tak zadajte: <i>textarea</i>.');
define('TEXYLA_FRM_ADD_TEXYLA_RULE', 'Vyplnte položku CSS id/trieda');
define('TEXYLA_FRM_ADD_DESCRIPTION_LABEL', 'Popis (poznámka)');

define('TEXYLA_FRM_ADD_ADMIN_SETTINGS_LABEL', 'Nastavenia Texyly pre administrátora');
define('TEXYLA_FRM_ADD_EDITOR_SETTINGS_LABEL', 'Nastavenia Texyly pre editora');
define('TEXYLA_FRM_ADD_USER_SETTINGS_LABEL', 'Nastavenia Texyly pre užívateľa');
define('TEXYLA_FRM_ADD_VISITOR_SETTINGS_LABEL', 'Nastavenia Texyly pre návštevníka');
define('TEXYLA_FRM_ADD_ALLOW_LABEL', 'Povoliť Texylu pre túto rolu');
define('TEXYLA_FRM_ADD_TEXYCFG_LABEL', 'Texy konfigurácia');
define('TEXYLA_FRM_ADD_BTLTOOLBAREDIT_LABEL', 'Tlačidlo editácie');
define('TEXYLA_FRM_ADD_BTLTOOLBARPREVIEW_LABEL', 'Tlačidlo náhľadu');
define('TEXYLA_FRM_ADD_BTLTOOLBARHTMLPREVIEW_LABEL', 'Tlačidlo HTML náhľadu');
define('TEXYLA_FRM_ADD_BUTTONTYPE_LABEL', 'Tvar tlačidla');
define('TEXYLA_FRM_ADD_TABS_LABEL', 'Záložky');
define('TEXYLA_FRM_ADD_HEADERS_LABEL', 'Nadpisy');
define('TEXYLA_FRM_ADD_FONT_STYLE_LABEL', 'Štýlovanie písma');
define('TEXYLA_FRM_ADD_TEXT_ALIGN_LABEL', 'Zarovnanie');
define('TEXYLA_FRM_ADD_LISTS_LABEL', 'Zoznamy');
define('TEXYLA_FRM_ADD_LINK_LABEL', 'Odkazy');
define('TEXYLA_FRM_ADD_IMG_LABEL', 'Obrázok');
define('TEXYLA_FRM_ADD_TABLE_LABEL', 'Tabuľky');
define('TEXYLA_FRM_ADD_EMOTICON_LABEL', 'Smajlíci');
define('TEXYLA_FRM_ADD_SYMBOL_LABEL', 'Symboly');
define('TEXYLA_FRM_ADD_COLOR_LABEL', 'Farby');
define('TEXYLA_FRM_ADD_TEXTTRANSFORM_LABEL', 'Transformácia textu');
define('TEXYLA_FRM_ADD_BLOCKS_LABEL', 'Bloky');
define('TEXYLA_FRM_ADD_CODES_LABEL', 'Označenie kódov');
define('TEXYLA_FRM_ADD_OTHERS_LABEL', 'Ostatné');
define('TEXYLA_FRM_ADD_ADMIN_CHECKS_LABEL', 'Voľby tlačítok');
define('TEXYLA_FRM_ADD_EDITOR_CHECKS_LABEL', 'Voľby tlačítok pre Editora');
define('TEXYLA_FRM_ADD_USER_CHECKS_LABEL', 'Voľby tlačítok pre Užívateľa');
define('TEXYLA_FRM_ADD_VISITOR_CHECKS_LABEL', 'Voľby tlačítok pre Návštevníka');

// errors
define('TEXYLA_ERR_NO_ID', 'Záznam s týmto ID neexistuje.');