<?php
/**
 * Module Ratings and Views
 * created by Branislav Zvolenský
 * 27.11.2010
 *
 * language: Slovak
 */
define('RAV_RENDER_DEFAULT_TITLE', 'Nastavenia RAV');
define('RAV_RATINGS_AFFECTED_CT_LABEL', 'Typy obsahu pre hodnotenia:');
define('RAV_VIEWS_AFFECTED_CT_LABEL', 'Typy obsahu pre počet zobrazení:');
define('RAV_RATINGS_AFFECTED_CT_DESC', 'Sem zapíšte strojové mená typov obsahu, na ktorých sa bude zobrazovať hodnotenie oddelené čiarkou. <a href="admin/content-types">Zoznam typov obsahu</a>');
define('RAV_VIEWS_AFFECTED_CT_DESC', 'Sem zapíšte strojové mená typov obsahu, na ktorých sa bude zobrazovať počet zobrazení oddelené čiarkou. <a href="admin/content-types">Zoznam typov obsahu</a>');
define('RAV_RATINGS_GENERAL_ON_LABEL', 'Zapnúť/vypnúť hodnotenia');
define('RAV_RATINGS_GENERAL_ON_DESC', 'Centrálne ovládanie zobrazovania hodnotení pre všetky zvolené typy obsahu.');
define('RAV_VIEWS_GENERAL_ON_LABEL', 'Zapnúť/vypnúť počet zobrazení');
define('RAV_VIEWS_GENERAL_ON_DESC', 'Centrálne ovládanie zobrazovania počtu zobrazení pre všetky zvolené typy obsahu.');
define('RAV_CHANGES_WERE_SAVED', 'Zmeny boli uložené.');
define('RAV_SAVING_FAILED', 'Uloženie zlyhalo.');
define('RAV_RATING_SAVED_MESSAGE', 'Ďakujeme za hodnotenie.');
define('RAV_RATING_UNSAVED_MESSAGE', 'Ukladanie hodnotenia zlyhalo.');
define('RAV_VIEWS_VIEWED', 'Zobrazené: ');

/*********** FORM INPUTS ***********/
define('RAV_FRM_RATINGS_SETTINGS', 'Nastavenia Hodnotenie a Zobrazenie');
define('RAV_FRM_RATINGS_DESC', 'Tu možete zapnuť zobrazenie hodnotenia a počtu zobrazení len pre tento obsah. Tieto nastavenia sú nezávislé na centrálnom nastavení modulu Ratings and Views');
define('RAV_FRM_RATINGS_LABEL', 'Zapnúť hodnotenie');
define('RAV_FRM_VIEWS_LABEL', 'Zapnúť zobrazenia');
define('RAV_RENDER_RATE_TITLE', 'Vysledok hlasovania');
