<?
/******* BOOL VARIABLES ***************/
Application::setVar('yes', 'Yes');
Application::setVar('no', 'No');

/******* GENERAL (TITLES, LABELS) *****/
define('HUM_NAME', 'Name');
define('NAME', 'Name');
define('MACHINE_NAME', 'Machine name');
define('TITLE', 'Title');
define('SAVE', 'Save');
define('DELETE', 'Delete');
define('ADD', 'Add');
define('EDIT', 'Edit');
define('ADD_NEW', 'Add new');
define('DEF', 'Default');
define('ACTIVE', 'Active');
define('ACTIONS', 'Actions');
define('IMAGE', 'Image');
define('FILE', 'File');
define('DESCRIPTION', 'Description');
define('PRIORITY', 'Priority');
define('UPLOAD', 'Upload');
define('ADD_IMAGE', 'Add image');
define('ADD_FILE', 'Add file');
define('SAVE_CHANGES', 'Save changes');
define('ITEM', 'Item');
define('CODE', 'Code');
define('SAVING_FAILED', 'Saving failed');
define('DELETED', 'Record was deleted');
define('URL_ALIAS', 'URL alias');
define('MENU', 'Menu');
define('LANGUAGE', 'Language');
define('ITEMS', 'Items');
define('MENU_TITLE', 'Menu title');
define('REQUIRED', 'Required');
define('ADD_NEW_FEMALE', 'Add new');
define('ADD_NEW_THEM', 'Add new');
define('CATEGORY', 'Category');
define('CATEGORIES', 'Categories');
define('SUBCATEGORY', 'Subcategory');
define('SUBCATEGORIES', 'Subcategories');
define('GOON', 'Continue');
define('DELETE_FAILED', 'Deleting failed');
define('SAVE_OK', 'The recrod was saved');
define('UNSORTED', 'Unsorted');
define('SELECT_CATEGORY', 'Select category');
define('AUTHOR', 'Author');
define('LAST_UPDATE', 'Last update');
define('VERSION', 'Version');
define('INSTALL_UNINSTALL', 'Install/Uninstall');
define('INSTALL', 'Install');
define('UNINSTALL', 'Uninstall');
define('SETTINGS', 'Settings');
define('SETTINGS_SAVED', 'Settings were saved');
define('LAST_LOGIN', 'Last login');
define('EMAIL', 'Email');
define('SURNAME', 'Surname');
define('PASSWORD', 'Password');
define('DATE', 'Date');
define('SEND', 'Send');
define('BODY', 'Body');
define('FIELDS', 'Fields');
define('FIELD', 'Field');
define('TYPE', 'Type');
define('MAKE_ORDER', 'Order');
define('YOU_HAVE_NO_PERMISION', 'You have no permision for this action.');
define('IS_REQUIRED', ' is required');
define('FIRST_MALE', 'First');
define('FIRST_FEMALE', 'First');
define('FIRST_THEM', 'First');
define('LAST_MALE', 'Last');
define('LAST_FEMALE', 'Last');
define('LAST_THEM', 'Last');
define('PAGE', 'Page');
define('OTHERS', 'Others');
define('SHOW', 'Show');
define('EXPAND', 'Expand');
define('PARENT_ITEM', 'Parent item');
define('LOCKED_ACCOUNT', 'This account was locked by administrator. If you have any question, contact the adminstrator of the page.');
define('UPDATE', 'Update');

define('1', 'Ano');
define('0', 'Nie');

/******* SYSTEM (APPLICATION) *****/
define('FOR_ALL_LANGS', 'All languages');
define('FRM_LANGUAGE_LABEL', 'Language Selection');

/******* ERRORS *******************/
define('APPLICATION_RUN_ERROR', 'An error occured by application run.');
define('MENUITEM_THE_SAME_SELECTED', 'It is not pissible to select self item as parent item.');