<?
/******* BOOL VARIABLES ***************/
Application::setVar('yes','Ano');
Application::setVar('no','Nie');

/******* GENERAL (TITLES, LABELS) *****/
define('HUM_NAME', 'Meno');
define('NAME', 'Názov');
define('MACHINE_NAME', 'Strojový názov');
define('TITLE', 'Titulok');
define('SAVE', 'Uložiť');
define('DELETE', 'Odstrániť');
define('ADD', 'Pridať');
define('EDIT', 'Upraviť');
define('ADD_NEW', 'Pridať nový');
define('DEF', 'Predvolené');
define('ACTIVE', 'Aktívne');
define('ACTIONS', 'Akcie');
define('IMAGE', 'Obrázok');
define('FILE', 'Súbor');
define('DESCRIPTION', 'Popis');
define('PRIORITY', 'Priorita');
define('UPLOAD', 'Nahrať');
define('ADD_IMAGE', 'Pridať obrázok');
define('ADD_FILE', 'Pridať súbor');
define('SAVE_CHANGES', 'Uložiť zmeny');
define('ITEM', 'Položka');
define('CODE', 'Kód');
define('SAVING_FAILED', 'Uloženie zlyhalo');
define('DELETED', 'Záznam bol vymazaný');
define('URL_ALIAS', 'URL alias');
define('MENU', 'Menu');
define('LANGUAGE', 'Jazyk');
define('ITEMS', 'Položky');
define('MENU_TITLE', 'Titulok v menu');
define('REQUIRED', 'Povinné');
define('ADD_NEW_FEMALE', 'Pridať novú');
define('ADD_NEW_THEM', 'Pridať nové');
define('CATEGORY', 'Kategória');
define('CATEGORIES', 'Kategórie');
define('SUBCATEGORY', 'Podkategória');
define('SUBCATEGORIES', 'Podkategórie');
define('GOON', 'Pokračovať');
define('DELETE_FAILED', 'Vymazanie zlyhalo');
define('SAVE_OK', 'Záznam bol uložený');
define('UNSORTED', 'Nezatriedný');
define('SELECT_CATEGORY', 'Výber kategórie');
define('AUTHOR', 'Autor');
define('LAST_UPDATE', 'Posledná aktualizácia');
define('VERSION', 'Verzia');
define('INSTALL_UNINSTALL', 'Inštalovať/Odinštalovať');
define('INSTALL', 'Inštalovať');
define('UNINSTALL', 'Odinštalovať');
define('SETTINGS', 'Nastavenia');
define('SETTINGS_SAVED', 'Nastavenia boli uložené');
define('LAST_LOGIN', 'Posledné prihlásenie');
define('EMAIL', 'Email');
define('SURNAME', 'Priezvisko');
define('PASSWORD', 'Heslo');
define('DATE', 'Dátum');
define('SEND', 'Odoslať');
define('BODY', 'Telo');
define('FIELDS', 'Polia');
define('FIELD', 'Pole');
define('TYPE', 'Typ');
define('MAKE_ORDER', 'Zoradiť');
define('YOU_HAVE_NO_PERMISION', 'Nemáte povolené vykonať túto akciu.');
define('IS_REQUIRED', ' je povinná');
define('FIRST_MALE', 'Prvý');
define('FIRST_FEMALE', 'Prvá');
define('FIRST_THEM', 'Prvé');
define('LAST_MALE', 'Posledný');
define('LAST_FEMALE', 'Posledná');
define('LAST_THEM', 'Posledné');
define('PAGE', 'Stránka');
define('OTHERS', 'Ostatné');
define('SHOW', 'Zobraziť');
define('EXPAND', 'Rozbaliť');
define('PARENT_ITEM', 'Nadradená položka');
define('LOCKED_ACCOUNT', 'Tento učet bol zablokovaný administrátorom. V prípade otázok kontaktujte administrátora stránky.');
define('UPDATE', 'Aktualizovať');


/******* SYSTEM (APPLICATION) *****/
define('FOR_ALL_LANGS', '--Všetky jazyky--');
define('FRM_LANGUAGE_LABEL', 'Výber jazyka');

/******* ERRORS *******************/
define('APPLICATION_RUN_ERROR', 'Pri behu aplikácie došlo k chybe');
define('MENUITEM_THE_SAME_SELECTED', 'Nie je možné zvoliť ako nadradenú položku vlastnú položku.');