<?php
define("DB_DRIVER", "sqlite"); //may be sqlite or mysql
define("DB_USER", "litepage");
define("DB_PASSWORD", "litepage");
define("DB_SERVER", "localhost");
define('SQLITE_DB', 'lightpage.sqlite');
define('MYSQL_DB', 'litepage');

define('NL', "<br/>\n");
define('FILES_DIR', WWW_DIR.'/files/');
define('IMAGES_DIR', WWW_DIR.'/images/');
define('SESSIONID', session_id());
//define('DEVELOPMENT', true);
//define('SQL_BROWSER', false);
?>